---
title: "Exercise25"
format: html
editor: visual
---

```{r}
# Get Data
library(sf)

rivers <- read_sf("data/majorrivers_0_0/MajorRivers.shp")
```

```{r}
# AOI 
miss_river <- rivers |> 
  dplyr::filter(grepl("Mississippi", NAME, ignore.case = TRUE))

# My AOI isn't working and keeps giving the same error
library(AOI)
library(tigris)
library(tidycensus)

counties_conus <- AOI::aoi_get(state = "conus")

```

```{r}
# Filter
miss_river <- st_transform(miss_river, st_crs(counties_conus))
river_counties <- st_filter(counties_conus, miss_river)

```

```{r}
# Make a Map
ggplot() +
  geom_sf(data = river_counties, fill = "lightblue", color = "grey20") +
  geom_sf(data = miss_river, color = "blue", size = 1) +
  theme_minimal()

```

```{r}
#Read in city data
cities <- read_csv("data/Data25/uscities.csv")

cities_sf <- st_as_sf(cities, coords = c("lng", "lat"), crs = 4326)
cities_sf <- st_transform(cities_sf, st_crs(river_counties))

```

```{r}
# Identify the cities around Mississippi River
cities_in_river_counties <- st_join(cities_sf, river_counties, left = FALSE)

cities_joined <- st_join(cities_sf, counties_conus, left = FALSE)

```

```{r}
# Calculae urban population
library(dplyr)

county_pop <- cities_joined %>%
  group_by(fip_code) %>%
  summarise(urban_pop = sum(population, na.rm = TRUE))

county_pop_df <- st_drop_geometry(county_pop)

counties_populated <- left_join(counties_conus, county_pop_df, by = "fip_code")

```

```{r}
# Add data
install.packages('viridis')
library(ggplot2)
library(viridis)

ggplot() +
  geom_sf(data = counties_populated, aes(fill = urban_pop), color = "white", size = 0.2) +
  geom_sf(data = miss_river, color = "blue", size = 0.6) +
  scale_fill_viridis_c(option = "plasma", na.value = "gray80", direction = -1) +
  theme_minimal() +
  labs(
    title = "Urban Population in Mississippi River Counties",
    fill = "Urban Pop."
  ) +
  theme(
    plot.title = element_text(size = 16, face = "bold", hjust = 0.5),
    legend.title = element_text(size = 12),
    legend.text = element_text(size = 10)
  )



print(map)


# Save
ggsave("images/mississippi_county_population.png", plot = map, width = 10, height = 7)

```
